default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: test123
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>

development:
  <<: *default
  database: portfolio_development

dev:
  <<: *default
  database: portfolio_dev

staging:
  <<: *default
  database: portfolio_staging

production:
  <<: *default
  database: portfolio_production

test: &test
  <<: *default
  database: portfolio_test

cucumber:
  <<: *test
